'use client';
import {useEffect,useState,useSyncExternalStore} from 'react';
import type {FormEvent} from 'react';
import {Dialog} from 'radix-ui';
import Image from 'next/image';
import {LayoutDashboard, MessagesSquare, Contact, Users, ChartColumn, Bell, Plug, Settings} from 'lucide-react';
import {initialData,sectors,states,health,waitMinutes,transition,decodeBackup} from '../lib/domain';
import type {Data,Ticket,State} from '../lib/domain';

const key='jp2auto-central-v2';
let cache:Data=initialData(),loaded=false,loadError='';
const listeners=new Set<()=>void>();
function hydrate(){if(loaded)return;loaded=true;try{const raw=localStorage.getItem(key);if(raw)cache=decodeBackup(raw);}catch{loadError='Não foi possível carregar o armazenamento. Exporte o conteúdo existente antes de substituir dados.';}}
function subscribe(fn:()=>void){listeners.add(fn);return()=>{listeners.delete(fn);};}
function snapshot(){hydrate();return cache;}
const server=initialData();
const serverSnapshot=()=>server;
function save(d:Data){if(loadError)throw Error(loadError);localStorage.setItem(key,JSON.stringify(d));cache=d;listeners.forEach(fn=>fn());}
function download(name:string,text:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const date=(v:string)=>v?new Date(v).toLocaleString('pt-BR'):'—';
const menuIcons=[LayoutDashboard,MessagesSquare,Contact,Users,ChartColumn,Bell,Plug,Settings];
const menu=['Visão geral','Atendimentos','Clientes e OS','Equipe','Indicadores','SLAs e alertas','Integrações','Configurações'];

export default function Home(){
 const data=useSyncExternalStore(subscribe,snapshot,serverSnapshot);
 const [tab,setTab]=useState('Visão geral'),[query,setQuery]=useState(''),[sector,setSector]=useState('Todos'),[state,setState]=useState('Todos'),[notice,setNotice]=useState(''),[editing,setEditing]=useState<Ticket|null>(null),[opened,setOpened]=useState(false),[selected,setSelected]=useState(''),[now,setNow]=useState(''),[mobile,setMobile]=useState(false);
 useEffect(()=>{const tick=()=>setNow(new Date().toISOString());const timeout=setTimeout(tick,0),timer=setInterval(tick,30000);return()=>{clearTimeout(timeout);clearInterval(timer);};},[]);
 function commit(d:Data,message:string){try{save(d);setNotice(message);return true;}catch(e){setNotice(e instanceof Error?e.message:'Não foi possível salvar. Exporte um backup.');return false;}}
 const time=now||new Date(0).toISOString();
 const rows=data.tickets.filter(t=>(sector==='Todos'||t.sector===sector)&&(state==='Todos'||t.state===state)&&`${t.client} ${t.code} ${t.os} ${t.protocol} ${t.id} ${t.owner} ${t.subject}`.toLowerCase().includes(query.toLowerCase()));
 const active=rows.filter(t=>t.state!=='Finalizado'),overdue=active.filter(t=>health(t,data.settings,time)==='Atrasado');
 const measured=rows.filter(t=>t.state==='Finalizado'),within=measured.filter(t=>t.elapsed<t.sla).length;
 const detail=data.tickets.find(t=>t.id===selected);
 const alerts=active.filter(t=>['Atrasado','Atenção'].includes(health(t,data.settings,time))||(t.followup&&new Date(t.followup)<=new Date(time)));
 const memberStats=data.members.map(m=>{const ts=rows.filter(t=>t.owner===m.id);const finished=ts.filter(t=>t.state==='Finalizado'),ratings=finished.filter(t=>t.rating>0);return {...m,count:ts.length,finished:finished.length,within:finished.length?Math.round(finished.filter(t=>t.elapsed<t.sla).length/finished.length*100):null,rating:ratings.length?(ratings.reduce((a,t)=>a+t.rating,0)/ratings.length).toFixed(1):'—',ratings:ratings.length};});
 function go(v:string){setTab(v);setMobile(false);setNotice('');}
 function formTicket(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),get=(k:string)=>String(f.get(k)||'').trim(),stamp=new Date().toISOString();const owner=get('owner'),dep=get('sector');if(owner&&!data.members.some(m=>m.id===owner&&m.sector===dep&&(m.active||owner===editing?.owner))){setNotice('Selecione um responsável do setor escolhido.');return;}
 if(!get('client')||!get('subject')||!get('nextActor')){setNotice('Preencha cliente, assunto e próxima ação.');return;}
 const nextState=get('state') as State,reason=get('reason');if(nextState==='Finalizado'&&!reason){setNotice('Informe o motivo da finalização.');return;}
 const base:Ticket=editing?transition(editing,nextState,data.settings,stamp,`Atualização: ${nextState}; setor ${dep}; responsável ${data.members.find(m=>m.id===owner)?.name||'Sem responsável'}. ${reason}`):{id:`JP2-${crypto.randomUUID().slice(0,8).toUpperCase()}`,client:'',code:'',os:'',protocol:'',origin:'',sector:dep,owner:'',subject:'',state:nextState,nextActor:'',followup:'',created:stamp,since:stamp,elapsed:0,sla:data.slas[dep],rating:0,events:[{at:stamp,text:`Atendimento cadastrado manualmente. ${reason}`}]};
 const t:Ticket={...base,client:get('client'),code:get('code'),os:get('os'),protocol:get('protocol'),origin:get('origin'),sector:dep,owner,subject:get('subject'),state:nextState,nextActor:get('nextActor'),followup:get('followup'),rating:Number(get('rating')),closed:nextState==='Finalizado'?stamp:undefined};
 if(commit({...data,tickets:editing?data.tickets.map(x=>x.id===t.id?t:x):[t,...data.tickets]},'Atendimento salvo.')){setOpened(false);setEditing(null);}}
 function filters(){return <div className="filters"><input aria-label="Buscar atendimentos" placeholder="Cliente, código, OS ou protocolo" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filtrar setor" value={sector} onChange={e=>setSector(e.target.value)}><option>Todos</option>{sectors.map(s=><option key={s}>{s}</option>)}</select><select aria-label="Filtrar situação" value={state} onChange={e=>setState(e.target.value)}><option>Todos</option>{states.map(s=><option key={s}>{s}</option>)}</select></div>;}
 function badge(t:Ticket){const h=health(t,data.settings,time);return <span className={`badge ${h==='Atrasado'?'red':h==='Atenção'?'amber':h==='No prazo'?'green':'gray'}`}>{h}</span>;}
 function ticketTable(){return <div className="scroll"><table><thead><tr><th>Cliente / vínculos</th><th>Setor / responsável</th><th>Situação</th><th>Espera útil acumulada</th><th>Ação</th></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td><strong>{t.client}</strong><small>{t.code?`Cliente ${t.code}`:'Vínculo pendente'} · OS {t.os||'—'}</small><small>{t.id} · Digisac {t.protocol||'não informado'}</small></td><td>{t.sector}<small>{data.members.find(m=>m.id===t.owner)?.name||'Sem responsável'}</small></td><td>{t.state}<small>{badge(t)}</small></td><td>{Math.floor(waitMinutes(t,data.settings,time))} min<small>Limite {t.sla} min</small></td><td><button onClick={()=>setSelected(t.id)}>Abrir</button></td></tr>)}</tbody></table>{!rows.length&&<p className="empty">Nenhum atendimento. Cadastre uma tratativa para começar.</p>}</div>;}
 function exportCSV(){const headers=['Protocolo local','Cliente','Código Bling','OS','Protocolo Digisac','Origem','Setor','Situação','Espera útil (min)'];const values=rows.map(t=>[t.id,t.client,t.code,t.os,t.protocol,t.origin,t.sector,t.state,Math.floor(waitMinutes(t,data.settings,time))]);const cell=(v:unknown)=>`"${String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')}"`;download('jp2auto-atendimentos.csv','\uFEFF'+[headers,...values].map(r=>r.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8');}
 return <div className="shell"><aside className={mobile?'sidebar visible':'sidebar'}><div className="brand"><Image className="brand-logo" src="/brand/jp2auto-yellow.png" alt="JP2 Auto" width={338} height={328} priority/><div><strong>JP2auto</strong><small>Central de atendimento · V2.1</small></div></div><nav>{menu.map((item,i)=><button className={tab===item?'current':''} key={item} onClick={()=>go(item)}><span>{(() => {const Icon=menuIcons[i];return <Icon size={18} aria-hidden="true"/>;})()}</span>{item}</button>)}</nav><div className="local"><strong>Piloto local</strong><p>Dados neste navegador. Integrações ainda não conectadas.</p></div></aside><main><header><button className="mobile" onClick={()=>setMobile(!mobile)}>Menu</button><div><small>CENTRAL OPERACIONAL</small><h1>{tab}</h1></div><button onClick={()=>go('SLAs e alertas')}>Alertas · {alerts.length}</button></header><div className="content"><div className="intro"><div><h2>{data.settings.company}</h2><p>Atendimento, pós-venda e acompanhamento das ordens de serviço.</p></div><button className="primary" onClick={()=>{setEditing(null);setOpened(true);}}>+ Novo atendimento</button></div><p className="banner">Modo local • sem sincronização com Digisac, Trello ou Bling • faça backups em Configurações.</p>{(notice||loadError)&&<p className="notice" role="status">{notice||loadError}</p>}
 {['Visão geral','Atendimentos','Clientes e OS','Indicadores','SLAs e alertas'].includes(tab)&&filters()}
 {tab==='Visão geral'&&<><div className="metrics"><article><small>Atendimentos abertos</small><b>{active.length}</b></article><article><small>Acima do prazo</small><b className="danger">{overdue.length}</b></article><article><small>Finalizados</small><b>{measured.length}</b></article><article><small>Finalizados dentro do limite</small><b>{measured.length?`${Math.round(within/measured.length*100)}%`:'—'}</b></article></div><section><h3>Fila de atendimento</h3>{ticketTable()}</section></>}
 {tab==='Atendimentos'&&<section><div className="section-head"><h3>Atendimentos e histórico</h3><button onClick={exportCSV}>Exportar CSV filtrado</button></div>{ticketTable()}</section>}
 {tab==='Clientes e OS'&&<section><h3>Vínculos registrados manualmente</h3><p>Código do cliente e Nº OS são referências do Bling. Estes dados ainda não foram validados na API.</p><div className="scroll"><table><thead><tr><th>Cliente</th><th>Código Bling</th><th>OS</th><th>Origem / protocolo</th><th></th></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td>{t.client}</td><td>{t.code||'Pendente de vinculação'}</td><td>{t.os||'—'}</td><td>{t.origin}<small>{t.protocol||'Sem protocolo Digisac'}</small></td><td><button onClick={()=>setSelected(t.id)}>Ver tratativa</button></td></tr>)}</tbody></table></div>{!rows.length&&<p className="empty">Os vínculos aparecerão após cadastrar os atendimentos.</p>}</section>}
 {tab==='Equipe'&&<><section><h3>Cadastrar colaborador</h3><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const name=String(f.get('name')).trim();if(!name)return;const m={id:crypto.randomUUID(),name,sector:String(f.get('sector')),active:true};if(commit({...data,members:[...data.members,m]},'Colaborador cadastrado.'))e.currentTarget.reset();}}><label>Nome<input name="name" required maxLength={120}/></label><label>Setor<select name="sector">{sectors.map(s=><option key={s}>{s}</option>)}</select></label><button className="primary">Cadastrar</button></form></section><section><h3>Colaboradores</h3>{!data.members.length&&<p>Cadastre os responsáveis de cada setor. Este cadastro não cria contas de acesso.</p>}{data.members.map(m=><form className="team-row" key={m.id} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);commit({...data,members:data.members.map(x=>x.id===m.id?{...m,name:String(f.get('name')).trim(),sector:String(f.get('sector'))}:x)},'Colaborador atualizado.');}}><input name="name" aria-label="Nome do colaborador" defaultValue={m.name} required/><select name="sector" aria-label="Setor do colaborador" defaultValue={m.sector}>{sectors.map(s=><option key={s}>{s}</option>)}</select><span>{m.active?'Ativo':'Inativo'}</span><button>Salvar</button><button type="button" onClick={()=>commit({...data,members:data.members.map(x=>x.id===m.id?{...m,active:!m.active}:x)},'Situação atualizada. Histórico preservado.')}>{m.active?'Desativar':'Ativar'}</button></form>)}</section></>}
 {tab==='Indicadores'&&<><section><h3>Volume registrado por setor</h3><p>Contagens dos registros filtrados. Sem dados demonstrativos.</p>{sectors.map(s=>{const n=rows.filter(t=>t.sector===s).length;return <div className="bar-row" key={s}><span>{s}</span><meter min={0} max={Math.max(rows.length,1)} value={n}/><b>{n}</b></div>;})}</section><section><h3>Prazo e avaliação por responsável</h3><p>O prazo compara a espera útil acumulada ao limite do atendimento. Avaliações são registros manuais, não auditoria automática.</p><div className="scroll"><table><thead><tr><th>Colaborador</th><th>Volume</th><th>Finalizados</th><th>Dentro do limite</th><th>Avaliação / amostra</th></tr></thead><tbody>{memberStats.map(m=><tr key={m.id}><td>{m.name}</td><td>{m.count}</td><td>{m.finished}</td><td>{m.within===null?'—':`${m.within}%`}</td><td>{m.rating} · {m.ratings} respostas</td></tr>)}</tbody></table></div></section></>}
 {tab==='SLAs e alertas'&&<><section><h3>Pendências calculadas</h3><p>Alertas locais enquanto a página está aberta. Nenhuma mensagem foi enviada ao Digisac ou Chat On.</p>{!alerts.length?<p className="empty">Nenhuma pendência nos filtros atuais.</p>:alerts.map(t=><div className="alert" key={t.id}><div><strong>{t.client} · OS {t.os||'—'}</strong><p>{health(t,data.settings,time)} · próxima ação: {t.nextActor||'Não definido'}{t.followup&&` · acompanhamento ${date(t.followup)}`}</p></div><button onClick={()=>setSelected(t.id)}>Tratar</button></div>)}</section><section><h3>Limite de espera útil por setor</h3><p>Aplicado aos novos atendimentos. Os existentes mantêm o limite original. Pendente interno continua contando; aguardando cliente pausa.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);commit({...data,slas:Object.fromEntries(sectors.map((s,i)=>[s,Number(f.get(`sla${i}`))]))},'Limites salvos para novos atendimentos.');}}><div className="form">{sectors.map((s,i)=><label key={s}>{s} (min)<input type="number" name={`sla${i}`} min={1} max={100000} defaultValue={data.slas[s]} required/></label>)}</div><button className="primary">Salvar limites</button></form></section></>}
 {tab==='Integrações'&&<section><h3>Preparação das integrações</h3><p>Os endereços abaixo servem como referência. Salvar não ativa sincronização. Não coloque tokens neste formulário.</p><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const digisac=String(f.get('digisac')),trello=String(f.get('trello'));if(![digisac,trello].every(v=>v.startsWith('https://'))){setNotice('Use endereços HTTPS.');return;}commit({...data,integrations:{digisac,trello}},'Referências salvas. Integrações continuam pendentes.');}}><label>Endereço Digisac<input type="url" name="digisac" defaultValue={data.integrations.digisac} required/></label><label>Quadro Trello<input type="url" name="trello" defaultValue={data.integrations.trello} required/></label><button className="primary">Salvar referências</button></form><table><thead><tr><th>Sistema</th><th>Vínculo previsto</th><th>Estado</th></tr></thead><tbody><tr><td>Bling</td><td>Código do cliente + Nº OS</td><td>Pendente de autorização</td></tr><tr><td>Trello</td><td>Nº OS + protocolo Digisac opcional</td><td>Pendente de sincronização</td></tr><tr><td>Digisac</td><td>Protocolo + código do cliente quando disponível</td><td>Pendente de documentação/API</td></tr><tr><td>Chat On</td><td>Destino dos alertas</td><td>Pendente de documentação/API</td></tr></tbody></table></section>}
 {tab==='Configurações'&&<><section><h3>Empresa e calendário de atendimento</h3><p>Horário do computador: {now?Intl.DateTimeFormat().resolvedOptions().timeZone:'—'}. O piloto usa esse fuso e não desconta feriados. Alterar o calendário recalcula o trecho ativo de espera.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const start=Number(f.get('start')),end=Number(f.get('end')),weekdays=f.getAll('day').map(Number);if(end<=start||!weekdays.length){setNotice('Informe um horário final maior que o inicial e ao menos um dia útil.');return;}commit({...data,settings:{company:String(f.get('company')),start,end,weekdays,warning:Number(f.get('warning'))}},'Configurações salvas.');}}><div className="form"><label>Empresa<input name="company" defaultValue={data.settings.company} required/></label><label>Início (hora cheia)<input name="start" type="number" min={0} max={23} defaultValue={data.settings.start} required/></label><label>Fim (hora cheia)<input name="end" type="number" min={1} max={24} defaultValue={data.settings.end} required/></label><label>Avisar ao atingir (%)<input name="warning" type="number" min={1} max={99} defaultValue={data.settings.warning} required/></label></div><div className="checks">{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map((d,i)=><label key={d}><input type="checkbox" name="day" value={i} defaultChecked={data.settings.weekdays.includes(i)}/>{d}</label>)}</div><button className="primary">Salvar configurações</button></form></section><section><h3>Backup local</h3><p>O backup contém dados dos clientes. Guarde-o em local restrito. Restaurar substitui os dados V2 deste navegador após confirmação.</p><button onClick={()=>download(`jp2auto-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(data,null,2))}>Exportar backup</button><label className="upload">Restaurar backup V2<input type="file" accept=".json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>5_000_000)throw Error('Limite de backup: 5 MB.');const restored=decodeBackup(await file.text());if(window.confirm('Substituir os dados atuais pelo backup? Exporte uma cópia antes de continuar.'))commit(restored,'Backup restaurado.');}catch(err){setNotice(err instanceof Error?err.message:'Backup inválido.');}e.target.value='';}}/></label><p>Os exemplos da V1 não são importados automaticamente. A chave antiga de armazenamento permanece intacta.</p></section></>}
 </div></main>
 <Dialog.Root open={opened} onOpenChange={setOpened}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="dialog"><Dialog.Title>{editing?'Editar atendimento':'Novo atendimento'}</Dialog.Title><Dialog.Description>Protocolo Digisac opcional. Cliente e OS podem ser vinculados depois.</Dialog.Description><form onSubmit={formTicket} className="form" key={editing?.id||'new'}><label>Cliente<input name="client" defaultValue={editing?.client} required maxLength={200}/></label><label>Código do cliente Bling<input name="code" defaultValue={editing?.code} maxLength={80}/></label><label>Nº OS<input name="os" defaultValue={editing?.os} maxLength={80}/></label><label>Protocolo Digisac (opcional)<input name="protocol" defaultValue={editing?.protocol} maxLength={120}/></label><label>Origem<select name="origin" defaultValue={editing?.origin||'Digisac'}>{['Digisac','Telefone','Presencial','Representante','E-mail','Outro'].map(x=><option key={x}>{x}</option>)}</select></label><label>Setor<select name="sector" defaultValue={editing?.sector||sectors[0]}>{sectors.map(x=><option key={x}>{x}</option>)}</select></label><label>Responsável<select name="owner" defaultValue={editing?.owner||''}><option value="">Sem responsável</option>{data.members.filter(m=>m.active||m.id===editing?.owner).map(m=><option value={m.id} key={m.id}>{m.name} · {m.sector}</option>)}</select></label><label>Situação<select name="state" defaultValue={editing?.state||states[0]}>{states.map(s=><option key={s}>{s}</option>)}</select></label><label>Quem deve agir agora?<input name="nextActor" defaultValue={editing?.nextActor||'Empresa'} required maxLength={120}/></label><label>Próximo acompanhamento<input name="followup" type="datetime-local" defaultValue={editing?.followup}/></label><label className="wide">Assunto<input name="subject" defaultValue={editing?.subject} required maxLength={300}/></label><label className="wide">Observação / motivo de encerramento<textarea name="reason" maxLength={2000}/></label><label>Avaliação do cliente<select name="rating" defaultValue={editing?.rating||0}><option value={0}>Não coletada</option>{[1,2,3,4,5].map(n=><option value={n} key={n}>{n}</option>)}</select></label><div className="wide actions"><button className="primary">Salvar atendimento</button><Dialog.Close asChild><button type="button">Cancelar</button></Dialog.Close></div></form><p role="status">{notice}</p></Dialog.Content></Dialog.Portal></Dialog.Root>
 <Dialog.Root open={!!detail} onOpenChange={v=>{if(!v)setSelected('');}}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="dialog"><Dialog.Title>{detail?.client}</Dialog.Title><Dialog.Description>{detail?.id} · OS {detail?.os||'—'} · Digisac {detail?.protocol||'não informado'}</Dialog.Description>{detail&&<><p>{detail.subject}</p><p>{detail.state} · {badge(detail)}</p><p>Próxima ação: {detail.nextActor} · acompanhamento: {date(detail.followup)}</p><p>Cadastrado: {date(detail.created)}{detail.closed&&` · finalizado: ${date(detail.closed)}`}</p><button onClick={()=>{setEditing(detail);setSelected('');setOpened(true);}}>Editar / transferir / finalizar</button><form className="note" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),text=String(f.get('note')).trim();if(!text)return;commit({...data,tickets:data.tickets.map(t=>t.id===detail.id?{...t,events:[...t.events,{at:new Date().toISOString(),text}]}:t)},'Observação registrada; o relógio de espera não foi reiniciado.');e.currentTarget.reset();}}><label>Registrar atualização<textarea name="note" required maxLength={2000}/></label><button>Adicionar ao histórico</button></form><h3>Histórico</h3><ol className="history">{detail.events.slice().reverse().map((e,i)=><li key={i}><small>{date(e.at)}</small>{e.text}</li>)}</ol></>}<Dialog.Close asChild><button>Fechar</button></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>
 </div>;
}
